### PR TITLE
Implement a blacklist for `--pty`

### LINKED ISSUE #12: Consider defaulting to `--no-pty` for some programs
Some processes executed through `host-spawn` fork, start other processes and terminate early. When they terminate, we close the pty and, due to how TTYs work, that might cause the process at the end of the spawn chain to be killed. 

I do not think there's anything we can do on our side, and I'm wondering whether we should consider to default to `--no-pty` when we're executing binaries that are known to fork and return immediately, while retaining the default behaviour for everything else.

List of known binaries that cause issues and require `--no-pty`:
* xdg-open (see #7)
* flatpak run (reproducible with `flatpak run net.runelite.RuneLite`)
* anything else?

A implementation of this would be to keep a list of problematic binary names, and based on the command line args, decide whether a pty is appropriate or not. A user might override our heuristic by explicitly passing a `--pty` or `--no-pty` option.

### PR DESCRIPTION
**Pull request by 89luca89**
This is to work on #12

This implements a very simple lookup table, that disables pty when a matching entry is found.

Fixes #12

Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>

### CODE REVIEW

**Comment by 1player** [comment]
Thanks for working on this, Luca.

I would like to be able to force using a pty even if the program is blacklisted by default. I'm thinking we could pair the option `--pty` with the existing `--no-pty`, and they always respect your choice. But if neither options are passed, it'll use the blocklist to determine if we should allocate a pty or not.

Also, any reason this is still a WIP? Are you planning on making further changes, or did you just want to have some feedback?

**Comment by 89luca89** [comment]
> any reason this is still a WIP? Are you planning on making further changes, or did you just want to have some feedback?

Yes I was waiting for feedbacks :smile: 

> I would like to be able to force using a pty even if the program is blacklisted by default. I'm thinking we could pair the option --pty with the existing --no-pty, and they always respect your choice. But if neither options are passed, it'll use the blocklist to determine if we should allocate a pty or not.

Makes sense, I'll work on it in the next days

**Comment by 89luca89** [comment]
@1player 

It should work automatically now if no flag is specified, and now there is a `--pty` flag to force it if wanted

**Comment by 1player** [comment]
Thanks. Looks good, let me know if you want to add more, or please just remove the WIP tag and I'll merge and cut a new release (as soon as I have a minute).

**Comment by 89luca89** [comment]
> Thanks. Looks good, let me know if you want to add more, or please just remove the WIP tag and I'll merge and cut a new release (as soon as I have a minute).

Yep i think that's it for now :-)

**Pull request merged**
